export const OBJCOLUMN = `
	[OBID] ,[DOMAINUID] ,[OBJUID] ,[OBJNAME],[OBJDEFUID] ,[CONFIG] ,[CREATIONDATE] ,[LASTUPDATED] ,[TERMINATIONDATE] ,[CREATIONUSER],[TERMINATIONUSER] ,[UNIQUEKEY] ,[CLAIMEDTOCONFIGS] ,[MARKEDFORREMOVAL] ,[DESCRIPTION]
	`;
export const TERMINATIONDATE = "TERMINATIONDATE = '9999/12/31-23:59:59:999'";